export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  stock: number;
  eta: number;
  image: string;
  qty?: string;
  mrp?: number;
  popular?: boolean;
};

const flickr = (kw: string, lock: number) =>
  `https://loremflickr.com/800/600/${kw}?lock=${lock}`;

export const categories = [
  "All Items",
  "Fruits & Vegetables",
  "Dairy & Eggs",
  "Munchies & Snacks",
  "Cold Drinks & Beverages",
  "Tea & Coffee",
  "Ice Cream & Desserts",
  "Instant Meals",
  "Staples",
  "Personal Care",
  "Stationery & Power",
];

export const products: Product[] = [
  {
    id: "1",
    name: "Flamin' Hot Cheetos",
    description: "Crunched, spicy, addictive.",
    price: 45,
    category: "Munchies & Snacks",
    stock: 8,
    eta: 3,
    image: flickr("chips,snack", 11),
  },
  {
    id: "2",
    name: "Chocolate Hazelnut Spread",
    description: "Easy scoop, endless options.",
    price: 120,
    category: "Munchies & Snacks",
    stock: 4,
    eta: 3,
    image: flickr("nutella,chocolate", 12),
  },
  {
    id: "3",
    name: "Protein Bar – Chocolate Fudge",
    description: "Sweet fix that fuels.",
    price: 85,
    category: "Munchies & Snacks",
    stock: 0,
    eta: 4,
    image: flickr("protein,bar", 13),
  },
  {
    id: "4",
    name: "Sparkling Water - Lime",
    description: "Crisp bubbles, fresh zest.",
    price: 50,
    category: "Cold Drinks & Beverages",
    stock: 15,
    eta: 2,
    image: flickr("water,bottle", 14),
  },
  {
    id: "5",
    name: "Iced Mango Slushie",
    description: "Tangy, sweet, icy.",
    price: 95,
    category: "Cold Drinks & Beverages",
    stock: 3,
    eta: 3,
    image: flickr("mango,smoothie", 15),
  },
  {
    id: "6",
    name: "Botanical Energy Drink - Citrus",
    description: "Zing without the crash.",
    price: 70,
    category: "Tea & Coffee",
    stock: 5,
    eta: 2,
    image: flickr("energy,drink,can", 16),
  },
  {
    id: "7",
    name: "Instant Coffee - Vanilla Coldbrew",
    description: "Ready in seconds.",
    price: 165,
    category: "Tea & Coffee",
    stock: 2,
    eta: 3,
    image: flickr("coffee,glass", 17),
  },
  {
    id: "8",
    name: "Mini Ice Cream Pint - Cookies",
    description: "Creamy cookie chunks.",
    price: 55,
    category: "Ice Cream & Desserts",
    stock: 12,
    eta: 4,
    image: flickr("icecream", 18),
  },
  {
    id: "9",
    name: "Chocolate Chip Cookies (4-pack)",
    description: "Soft, chewy, gone fast.",
    price: 75,
    category: "Ice Cream & Desserts",
    stock: 3,
    eta: 4,
    image: flickr("cookies,chocolate", 19),
  },
  {
    id: "10",
    name: "Instant Noodle Cup - Spicy",
    description: "Hot, fast, fragrant.",
    price: 40,
    category: "Instant Meals",
    stock: 18,
    eta: 3,
    image: flickr("noodles,cup", 20),
  },
  {
    id: "11",
    name: "Microwave Popcorn - Sour Cream",
    description: "Buttery, crunchy, done.",
    price: 35,
    category: "Instant Meals",
    stock: 7,
    eta: 3,
    image: flickr("popcorn", 21),
  },
  {
    id: "12",
    name: "Hand Sanitizer - 50ml",
    description: "Quick clean, on the go.",
    price: 60,
    category: "Personal Care",
    stock: 5,
    eta: 3,
    image: flickr("sanitizer", 22),
  },
  {
    id: "13",
    name: "Disposable Toothbrushes (5-pack)",
    description: "Fresh mouth, no fuss.",
    price: 45,
    category: "Personal Care",
    stock: 0,
    eta: 4,
    image: flickr("toothbrush", 23),
  },
  {
    id: "14",
    name: "AA Batteries (4-pack)",
    description: "Power your devices now.",
    price: 180,
    category: "Stationery & Power",
    stock: 9,
    eta: 3,
    image: flickr("batteries", 24),
  },
  {
    id: "15",
    name: "USB-C Charging Cable",
    description: "Fast charge, no fuss.",
    price: 220,
    category: "Stationery & Power",
    stock: 4,
    eta: 3,
    image: flickr("usb,cable", 25),
  },
  {
    id: "16",
    name: "Gummy Bears - Mixed",
    description: "Sweet, sour, chewy.",
    price: 55,
    category: "Munchies & Snacks",
    stock: 10,
    eta: 3,
    image: flickr("gummy,candy", 26),
  },
  {
    id: "17",
    name: "Blue Raspberry Slushie",
    description: "Tangy, sweet, icy.",
    price: 95,
    category: "Cold Drinks & Beverages",
    stock: 3,
    eta: 3,
    image: flickr("slushie,blue", 27),
  },
  {
    id: "18",
    name: "Energy Shot - Guarana",
    description: "Quick lift in a shot.",
    price: 70,
    category: "Tea & Coffee",
    stock: 0,
    eta: 4,
    image: flickr("shot,drink", 28),
  },
  {
    id: "19",
    name: "Frozen Pizza - Pepperoni",
    description: "Out of oven in 10.",
    price: 150,
    category: "Instant Meals",
    stock: 6,
    eta: 5,
    image: flickr("pizza", 29),
  },
  {
    id: "20",
    name: "Neon Paint Markers (set)",
    description: "Glow in the dark.",
    price: 195,
    category: "Stationery & Power",
    stock: 2,
    eta: 4,
    image: flickr("markers,pens", 30),
  },
  {
    id: "21",
    name: "Tomato Hybrid",
    description: "Fresh daily stock.",
    price: 29,
    qty: "500 g",
    mrp: 40,
    category: "Fruits & Vegetables",
    stock: 24,
    eta: 3,
    image: flickr("tomato", 31),
    popular: true,
  },
  {
    id: "22",
    name: "Potato",
    description: "Farm-fresh, hand picked.",
    price: 35,
    qty: "1 kg",
    mrp: 50,
    category: "Fruits & Vegetables",
    stock: 30,
    eta: 3,
    image: flickr("potato", 32),
    popular: true,
  },
  {
    id: "23",
    name: "Onion",
    description: "Sharp, everyday essential.",
    price: 45,
    qty: "1 kg",
    mrp: 60,
    category: "Fruits & Vegetables",
    stock: 26,
    eta: 3,
    image: flickr("onion", 33),
  },
  {
    id: "24",
    name: "Banana Robusta",
    description: "Ripe and ready.",
    price: 40,
    qty: "500 g",
    mrp: 55,
    category: "Fruits & Vegetables",
    stock: 18,
    eta: 3,
    image: flickr("banana", 34),
    popular: true,
  },
  {
    id: "25",
    name: "Amul Taaza Milk",
    description: "Toned milk, chilled.",
    price: 27,
    qty: "500 ml",
    mrp: 30,
    category: "Dairy & Eggs",
    stock: 20,
    eta: 3,
    image: flickr("milk", 35),
    popular: true,
  },
  {
    id: "26",
    name: "Farm Eggs (6-pack)",
    description: "Protein for the week.",
    price: 48,
    qty: "6 pcs",
    mrp: 60,
    category: "Dairy & Eggs",
    stock: 15,
    eta: 3,
    image: flickr("eggs", 36),
  },
  {
    id: "27",
    name: "Whole Wheat Atta",
    description: "Chakki-fresh, coarse grind.",
    price: 89,
    qty: "5 kg",
    mrp: 120,
    category: "Staples",
    stock: 12,
    eta: 4,
    image: flickr("flour,wheat", 37),
  },
  {
    id: "28",
    name: "Toor Dal",
    description: "Polished, protein-rich.",
    price: 95,
    qty: "1 kg",
    mrp: 130,
    category: "Staples",
    stock: 10,
    eta: 4,
    image: flickr("lentils,dal", 38),
  },
];