/**
 * Generates the two artefacts the build tools can actually consume:
 *
 *   dist/tailwind.cjs  — CommonJS, for the native app's Tailwind v3
 *                        `tailwind.config.js`, which cannot import TS/ESM.
 *   dist/tokens.css    — CSS custom properties for the web apps'
 *                        Tailwind v4 `@theme` blocks.
 *
 * Both are COMMITTED so a fresh clone builds without a codegen step, and
 * both are covered by a drift test that regenerates and compares. That is
 * the trade: a derived file in git, in exchange for it being impossible
 * for the derived file to disagree with the source unnoticed.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { craaveeTheme } from "./src/tailwind.ts";
import { cssVariables } from "./src/css.ts";
import { motion } from "./src/index.ts";

const HEADER = "/* GENERATED by packages/tokens/build.ts — do not edit by hand. */";

export function tailwindCjs(): string {
  return `${HEADER}\nmodule.exports = ${JSON.stringify(
    { consumer: craaveeTheme("consumer"), ops: craaveeTheme("ops") }, null, 2,
  )};\n`;
}

export function tokensCss(): string {
  return [
    `/* GENERATED by packages/tokens/build.ts — do not edit by hand. */`,
    `:root {`,
    cssVariables("consumer"),
    `}`,
    ``,
    `/* Operational surfaces (Store, Console) opt in by setting this on <html>. */`,
    `[data-surface="ops"] {`,
    cssVariables("ops"),
    `}`,
    ``,
    `/* Reduced motion is honoured globally, not per component: a screen`,
    `   should not be able to forget it. Durations collapse to --duration-instant`,
    `   rather than to 0 so transitions still complete deterministically. */`,
    `@media (prefers-reduced-motion: reduce) {`,
    `  *, *::before, *::after {`,
    `    animation-duration: ${motion.duration.instant}ms !important;`,
    `    animation-iteration-count: 1 !important;`,
    `    transition-duration: ${motion.duration.instant}ms !important;`,
    `    scroll-behavior: auto !important;`,
    `  }`,
    `}`,
    ``,
  ].join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  mkdirSync(new URL("./dist/", import.meta.url), { recursive: true });
  writeFileSync(new URL("./dist/tailwind.cjs", import.meta.url), tailwindCjs());
  writeFileSync(new URL("./dist/tokens.css", import.meta.url), tokensCss());
  console.log("tokens: wrote dist/tailwind.cjs and dist/tokens.css");
}
